export enum PatternTypeEnum {
    UNIFORM = "UNIFORM",
    VERTICAL_LINED = "VERTICAL_LINED",
    HORIZONTAL_LINED = "HORIZONTAL_LINED",
    GRID = "GRID",
    GRADIENT = "GRADIENT",
    TEXTURE = "TEXTURE",
}